- menu_name: "Autres..."

- name: "Coupures de presse"
  url: "/journaux/"
  title: "Journaux"

- name: "Newsletter"
  url: "/newsletter/"
  title: "Newsletter"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   title: "Sitemap for Google Webmaster Tools"
