- menu_name: "Autres..."

- name: "Journaux"
  url: "/news/"
  title: "Coupures de presse"

# - name: "Sponsors"
#   url: "/feed.xml"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   title: "Sitemap for Google Webmaster Tools"
